"""
Write graveyard report to disk as Markdown and JSON.
"""

import json
import logging
from datetime import datetime
from pathlib import Path

from backend.config import OUTPUT_PATH

logger = logging.getLogger(__name__)


async def write_graveyard_report(report_data: dict) -> list[str]:
    """Write report to timestamped Markdown + JSON files. Returns file paths."""
    OUTPUT_PATH.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
    repo = report_data.get("project_path", "unknown")
    features: list[dict] = report_data.get("features", [])

    revive_now = [f for f in features if f.get("viability", {}).get("recommendation") == "revive_now"]
    investigate = [f for f in features if f.get("viability", {}).get("recommendation") == "investigate_further"]
    keep_buried = [f for f in features if f.get("viability", {}).get("recommendation") == "keep_buried"]

    md = _build_markdown(repo, features, revive_now, investigate, keep_buried, timestamp)

    md_path = OUTPUT_PATH / "graveyard_report.md"
    ts_md_path = OUTPUT_PATH / f"graveyard_report_{timestamp}.md"
    json_path = OUTPUT_PATH / "graveyard_report.json"
    ts_json_path = OUTPUT_PATH / f"graveyard_report_{timestamp}.json"

    md_path.write_text(md, encoding="utf-8")
    ts_md_path.write_text(md, encoding="utf-8")
    json_path.write_text(json.dumps(report_data, indent=2, default=str), encoding="utf-8")
    ts_json_path.write_text(json.dumps(report_data, indent=2, default=str), encoding="utf-8")

    logger.info("[OK] Graveyard report written → %s", md_path)
    return [str(md_path), str(json_path)]


def _build_markdown(repo, features, revive_now, investigate, keep_buried, timestamp) -> str:
    lines = [
        "# GRAVEYARD REPORT",
        f"**Repository:** {repo}",
        f"**Scan date:** {datetime.now().strftime('%B %d, %Y')}",
        f"**Features analyzed:** {len(features)}",
        "",
        "---",
        "",
        "## Summary",
        "",
        f"| Category | Count |",
        f"|---|---|",
        f"| Revive Now | {len(revive_now)} |",
        f"| Investigate Further | {len(investigate)} |",
        f"| Keep Buried | {len(keep_buried)} |",
        "",
        "---",
        "",
    ]

    if revive_now:
        lines += ["## REVIVE NOW", ""]
        for f in revive_now:
            lines += _feature_section(f, "REVIVE")

    if investigate:
        lines += ["## INVESTIGATE FURTHER", ""]
        for f in investigate:
            lines += _feature_section(f, "INVESTIGATE")

    if keep_buried:
        lines += ["## KEEP BURIED", ""]
        for f in keep_buried:
            dr = f.get("death_reason", {})
            lines.append(f"- **{f['name']}** — {dr.get('primary_reason', 'kill reason unknown')} (constraint still applies)")
        lines.append("")

    lines += [
        "---",
        "",
        f"*Generated by NECRO — The Code Necromancer*",
        f"*GitLab MCP tools used: list_commits, get_commit, list_issues, list_merge_requests, list_merge_request_notes, list_issue_notes, search_code*",
        f"*Scan timestamp: {timestamp}*",
    ]

    return "\n".join(lines)


def _feature_section(f: dict, status: str) -> list[str]:
    name = f.get("name", "unknown")
    kill_date = f.get("kill_date", "unknown")
    kill_msg = f.get("kill_commit_message", "")
    sha = f.get("kill_commit_sha", "")
    dr = f.get("death_reason", {})
    vi = f.get("viability", {})
    roi = f.get("roi", {})

    lines = [
        f"### {name}",
        f"**Killed:** {kill_date}" + (f" (commit `{sha[:8]}`)" if sha else ""),
        f"**Kill reason:** {dr.get('primary_reason', kill_msg)}",
        f"**Category:** {dr.get('category', 'unknown')}",
        "",
    ]

    if status == "REVIVE":
        lines += [
            f"**What has changed:** {vi.get('what_changed', 'See viability assessment')}",
            f"**Estimated effort:** {vi.get('effort_estimate', 'unknown')}",
            f"**Revival feasibility:** {vi.get('revival_feasibility', '?')}/10",
            f"**ROI estimate:** {roi.get('roi_estimate_label', 'not estimated')} *(rough estimate based on available signals)*",
            "",
        ]
        risks = vi.get("technical_risks", [])
        if risks:
            lines += ["**Technical risks:**"] + [f"- {r}" for r in risks] + [""]
        lines.append(f"**Recommendation:** {vi.get('reasoning', '')}")

    elif status == "INVESTIGATE":
        lines += [
            f"**Status:** Constraint may be partially resolved — investigation recommended",
            f"**Reasoning:** {vi.get('reasoning', '')}",
        ]

    cited = dr.get("cited_evidence", "")
    if cited:
        lines.append(f"\n> *{cited}*")

    lines += ["", "---", ""]
    return lines
